language: android
dist: trusty
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
  components:
    - tools
    - build-tools-29.0.2
    - platform-tools
    - tools

before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  - echo 'count=0' > /home/travis/build/Djangoogle/Module/local.properties

install:
  - sdkmanager --list || true
  - sdkmanager --uninstall "build-tools;25.0.2"
  - sdkmanager --uninstall "build-tools;28.0.3"
  - sdkmanager --uninstall "emulator"
  - sdkmanager --uninstall "platforms;android-25"
  - echo yes | sdkmanager "platforms;android-29"
  - echo yes | sdkmanager "build-tools;29.0.2"
  - echo yes | sdkmanager "extras;google;google_play_services"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "tools"
  - sdkmanager --list || true

script:
  - ./gradlew clean build