language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.2
    - android-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
  before_install:
    - yes | sdkmanager "platforms;android-29"
    - chmod +x gradlew
script:
  - ./gradlew clean assembleDebug